//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public int EmpleadoID { get; set; }
        public string Nombre { get; set; }
        public int PuestoID { get; set; }
        public int DepartamentoID { get; set; }
    
        public virtual Departamento Departamento { get; set; }
        public virtual Puesto Puesto { get; set; }
    }
}
